---
apiVersion: v1
kind: ConfigMap
metadata:
  name: journalbeat-config
  namespace: alazyer-system
  labels:
    k8s-app: journalbeat
data:
  journalbeat.yml: |-
    journalbeat.inputs:
    - paths: ["/var/log/journal"]
      seek: cursor

    output.elasticsearch:
      hosts: ${ELASTICSEARCH_HOSTS}
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: journalbeat
  namespace: alazyer-system
  labels:
    k8s-app: journalbeat
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        k8s-app: journalbeat
    spec:
      containers:
      - name: journalbeat
        image: docker.elastic.co/beats/journalbeat:6.7.2
        imagePullPolicy: Always
        args: [
          "-c", "/etc/journalbeat.yml",
          "-e",
        ]
        env:
        - name: ELASTICSEARCH_HOSTS
          value: "[elasticsearch:9200]"
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: config
          mountPath: /etc/journalbeat.yml
          readOnly: true
          subPath: journalbeat.yml
        - name: data
          mountPath: /usr/share/journalbeat/data
        - name: varlogjournal
          mountPath: /var/log/journal
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: dockersock
          mountPath: /var/run/docker.sock
      volumes:
      - name: config
        configMap:
          defaultMode: 0600
          name: journalbeat-config
      - name: varlogjournal
        hostPath:
          path: /var/log/journal
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      - name: data
        emptyDir: {}
